# This is a basic workflow that is manually triggered

name: Trello workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  issues:
    types: [opened, edited]
    
jobs:
  TrelloIssue:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Link GitHub Issue and Pull Request with Trello Card
      uses: jessicazu/trello-github-actions@v1.0
      env:
        TRELLO_API_KEY: f4912fa0a4f8b65009b7c563b904261b
        TRELLO_API_TOKEN: ${{ secrets.TRELLO_TOKEN }}
        TRELLO_BOARD_ID: 5f3ec5457ef52c3882ac185f
        TRELLO_LIST_ID: 5f3ec743ddc6e422eaa346e3
        TRELLO_DEPARTURE_LIST_ID: create_card_when_issue_open
        TRELLO_DESTINATION_LIST_ID: move_card_when_pull_request_closed  
      with:
        # Action to do
        trello-action: create_card_when_issue_opened
